### ISSUE TITLE
Single test run creates multiple launches in RP when capabilities.shardTestFiles = true

### ISSUE THREAD

**Issue by yuriiveremiienko** [fedoseev-vitaliy/mocha-rp-reporter#3]
"mocha": "^3.4.2",
"mocha-rp-reporter": "^1.0.12",

when `capabilities.shardTestFiles` option is enabled new launch in RP created for every spec file in test run.

**Comment by fedoseev-vitaliy** [comment]
@yuriiveremiienko this is seems to be an expected behavior, as with `capabilities.shardTestFiles` tests run in multiple processes and cause of it it will create multiple runs in RP. I would suggest to use https://www.npmjs.com/package/mocha.parallel instead of sharding in case of API test.
